const express = require("express");
const { loginController, registerController, sendOtpController, forgotPasswordController, changePasswordController, logoutController } = require("../Controller/common/auth.controller");
const { authMiddleware, forgotPasswordMiddleware } = require("../Middlewares/auth.middleware");
const { dashboardController } = require("../Controller/common/dashboard");
const routes = express.Router();
routes.post("/logout", logoutController);
routes.post("/changePassword", authMiddleware, changePasswordController);
routes.post("/forgotPassword", forgotPasswordMiddleware, forgotPasswordController);
routes.post("/login", loginController);
routes.post("/dashboard", authMiddleware, dashboardController);
routes.post("/register", registerController);
routes.post("/sendOtp",sendOtpController);
module.exports = routes;