const express = require("express");
const { loginController, registerController } = require("../Controller/common/auth.controller");
const authMiddleware = require("../Middlewares/auth.middleware");
const routes = express.Router();
routes.post("/logout", authMiddleware, logoutController);
routes.post("/changePassword", authMiddleware, changePasswordController);
routes.post("/forgotPassword", forgotPasswordController);
routes.post("/login", loginController);
routes.post("/dashboard", authMiddleware, dashboardController);
routes.post("/register", registerController);
routes.post("/sendOtp", sendOtpController);
routes.post("/verifyOtp", verifyOtpController);
module.exports = routes;